In [2]:
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\uos\Anaconda3

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.1                |           py37_0         2.8 MB
    cudatoolkit-10.0.130       |                0       250.0 MB
    ninja-1.9.0                |   py37h74a9793_0         238 KB
    pytorch-1.2.0              |py3.7_cuda100_cudnn7_1       479.3 MB  pytorch
    torchvision-0.4.0          |       py37_cu100         2.3 MB  pytorch
    ------------------------------------------------------------
                                           Total:       734.6 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.0.130-0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  pytorch  

In [1]:
conda list torch


# packages in environment at C:\Users\uos\Anaconda3:
#
# Name                    Version                   Build  Channel
pytorch                   1.2.0           py3.7_cuda100_cudnn7_1    pytorch
torchvision               0.4.0                py37_cu100    pytorch

Note: you may need to restart the kernel to use updated packages.


In [9]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [10]:
#Creating Tensors
V_data = [1.,2.,3.]
V = torch.tensor(V_data)
print(V)

M_data = [[1.,2.,3.],[4.,5.,6.]]
M = torch.tensor(M_data)
print(M)

T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [11]:
#Index into V and get a scalar(0 dimentional tensor)
print(V[0])
#Get a Python number from it
print(V[0].item())
print(M[0])
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [12]:
x = torch.randn((3,2,2))
print(x)

tensor([[[ 0.6614,  0.2669],
         [ 0.0617,  0.6213]],

        [[-0.4519, -0.1661],
         [-1.5228,  0.3817]],

        [[-1.0276, -0.5631],
         [-0.8923, -0.0583]]])


In [14]:
#Operations with Tensors
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
c = torch.cat([x,y])
print(z)
print(c)

tensor([5., 7., 9.])
tensor([1., 2., 3., 4., 5., 6.])


In [15]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[-0.1955, -0.9656,  0.4224,  0.2673, -0.4212],
        [-0.5107, -1.5727, -0.1232,  3.5870, -1.8313],
        [ 1.5987, -1.2770,  0.3255, -0.4791,  1.3790],
        [ 2.5286,  0.4107, -0.9880, -0.9081,  0.5423],
        [ 0.1103, -2.2590,  0.6067, -0.1383,  0.8310]])
tensor([[-0.2477, -0.8029,  0.2366,  0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [ 0.2857,  0.6898, -0.6331, -0.5525,  0.6355, -0.3968, -0.6571, -1.6428]])
